################################
# GENERAL CONFIGURATION
################################
language: python
# We are going to need a full-VM to run docker containers inside.
# Besides coko tests needs sudo to test chown related features.
sudo: enabled
dist: xenial
group: travis_latest
# Vdist needs docker enabled to work.
services:
- docker

################################
# TEST MATRIX
################################
python:
- 3.7
- nightly
#env:
# global:
# - secure: "Ig3i1GxGTxz+J1LR46cmkkWzpHBUsUVpTVJZ5nyrH6781eoQmZStNfBdmn32MogumbyTnQzUEtWHEdAMErwtmOcCOo0LkrHKYNlJopVA06NwO7+IO8FGpSEydeMYFMsWdEO8Hg2vk/xr+K7UjVcJvG0usPxpEpIE17abif64mnDJXuB3VHchi/0I1BYimnmXVVFh93A+xOdXxbYjnPCDSQQ+f85NqTyMw1aTCkYuqG1XOZBdrO0rGd8McHjdbwLFOmN0Ve6SaollosztA/AgI5VcfsCn4tlSpg6DmY976QWkWchVVQI33vJEYGXiA4VFLzfGJsobQQZHuAieLBsvgj3Lz8OVVItnIPYVOcJ1qDbQP09VZKxFo9zDajJq1169oYSFlOj/0KrHJYEIGHwk+kwBWn6THdnadY8qeko1TEdWfrsgn3gmCUK9njQCA5UJM+7dPTWTE++fSBc0dZqXLV8ooPJ7ZjCMX7BCG0PR9Sr2PRLwOFtGYpWzdu4hIM8r8TBLZfo85LcGwa+mhOtfD+bdxCoYyvsmQzgGpcVWqJc76WuvemHSjmpV08mKu3UHyRPrmUP2yrD700u05kj9G6mpu0ZGzQgq567YaUy/jaQp2esNNhZ4PNdDvKtatUDY7OQ9RXguNKSYNI+b+7IgDdK3vQ4uCBMjDP4F1VEulJ0="
# matrix:
#  - TEST_TAG="test_generate_deb"
#  - TEST_TAG="centos6"
#  - TEST_TAG="centos7"
matrix:
  # Actually I only build with latest stable python release, but I want
  # to be aware in advance if any dev python version is going to crash
  # my future builds.
  allow_failures:
  - python: nightly

################################
# BRANCH FILTER
################################
branches:
  only:
  - staging

################################
# RESULT NOTIFICATIONS
################################
notifications:
  recipients:
  - dante.signal31@gmail.com
  on_sucess: always
  on_failure: always

################################
# TESTING
################################
before_install:
#  - sudo apt-get update -qq
#  # To test we need docker.io but that comes already packaged in travis image
#  # so we don't need to install it.
#  - sudo apt-get install -qq libssl1.0.0 rpm
install:
  - pip install -r requirements.txt
script:
  - sudo python -m unittest discover