################################
# GENERAL CONFIGURATION
################################
language: python
# We are going to need a full-VM to run docker containers inside.
# Besides coko tests needs sudo to test chown related features.
sudo: enabled
dist: xenial
group: travis_latest
# Vdist needs docker enabled to work.
services:
- docker

################################
# TEST MATRIX
################################
python:
- 3.7

################################
# BRANCH FILTER
################################
branches:
  only:
  - staging

################################
# RESULT NOTIFICATIONS
################################
notifications:
  recipients:
  - dante.signal31@gmail.com
  on_sucess: always
  on_failure: always

################################
# TESTING
################################
script:
  # If I call simply python3 Travis launch it system wide python3, not the
  # specially installed python3 for this build. So I have to use the
  # full path to the created. virtualenv.
  - sudo ~/virtualenv/python3.7/bin/python3 -m unittest discover

################################
# DEPLOYMENT
################################
jobs:
  include:
  # Update master branch.
  - stage: Branch merge to production branch
    python: 3.7
    env:
    - PYTHONPATH="${PYTHONPATH}:${TRAVIS_BUILD_DIR}"
    if: branch = staging
    script:
    - ci_scripts/merge_with_production
  # Upload packages to Python Package Index.
  - stage: Pypi deployment
    python: 3.7
    script: echo "Deploying to Python Package Index..."
    deploy:
    - provider: pypi
      user:
        secure: "DUgDI1bayvA2uPQRck4jT9GEiRLgGjh+zSZVqZrdO7rR8LG3JDdsuGxYUOyvoH498q4uUY6a4VoN+VcxOHyDbXkMSEz91P29rj5lKAnyk3X0+iI81HyF42BMvOB4BzNpn5ym9LWmPpijDX09NRC50EvqMZTWxOabvOmmbLRoc21h2pPce+4Qs6YK6p3QSKVKRXISRMmH6VoSSSO1dMFDvF8NKt+H4v8SFsBdQae5VFd4/srHlBH2cF1Atow/Y3SPtqG3Y4Ln40noTowgO0Sh2Gry/6ioGeURaYGLWdKPyvHuLQTqR8GOkzvlkbY0gSjTkCVDzoqfLepDwJW0x8sw37LE/4HB18YxhT/d3IHPgESU2wttVeNA3/RHGOy/aXJDQrs81lPIZyJHNmBaJJpkvV6jRct80c0xSaWiH5X/DomLpxKpf5e+Itca5sCV5rwnf31AW05B2sdoEq6UxQMeoNJ5o5+3yM8H9HWwfZ88sSgcgqENnye6QxDPIMXGgXyMZ7qiuFhucsxbQ8SqMetAtc/yq08szuFVqGuSkRBGbPpP/QgebY885TdKsGCCUUNf1YmzNksYRaDvmPGizpxYPPgkSqehIAocVYC8WPwHYe4yio25UVFbt/QixSiBEOx1+G8Qb/OY/Hqpn4rZsqmuYUgzfxtUm5LzGXG565dI7dE="
      password:
        secure: "X7LVEIqj77L8N8ZRY4rPyQunL44GqnzwCdvXF8n03OUIC+U4WVC5QXMdcZ8PnJBJHxI1jQuascZGBT4+xO97sMWlCFZxHGLDkWTJkp3fqxIaO5BjpGEl3Ofl1qAHMhchknRdko18bFiE6sm/PLbg66rspBlepSGsGLf/3j9DIMIx9voWD5VnspBFLnhMEUmtyjrk+ORIR0O7mXPrgEkyZGdGRly4Tuo8jTg0v7LbskkkNDJDYtwfiGLkDSK0+5TuMiLuzo4Zf3pe2+clTvqzN+xx/2mW5w46/bYNNTqoFRPwN3X2MGCddnR07Njo4XHTaI+6gXh1/Dwax5Q/zsf8IrSNS9yBbco5eQx/0FlZuVzIFxPsWJbd90V0a5914zP3U3rJoWMULCje/dBW06atDEvCojMOXBiLmtAd3kbXdifrzcO+CPjBI8SaBaSRC48szRUeIoRkSKLzGz/c/wehU7BfV/8UQZ4ds+XCYfnKCzA66pzwOnSOXeRnV3EJAcugZhpY6trohKzFZxEECBhYu3DZXV49vZChWtKWUoc+WznDAR36wFlvOLMA4eZV4CVgSnNnqd26iaSLOYGNDbT956Z98mzV4MmAAuqAlaEWoj12c5qWOBd9N2wayCKd1YsPbZ+sdBwPht5MKJy8Nf61zF3LgABXndY0pITSdxEkRk0="
      distributions: "sdist bdist_wheel"
      on:
      branch: staging