#!/usr/bin/env bash

 
DO NOT EDIT DIRECTLY THIS FILE AS IT IS AUTOMATICALLY GENERATED BYci_scripts/create_postinst_script SCRIPT.

# Link geolocate executable from /usr/bin.
ln -s /opt/coko/bin/coko /usr/bin/coko

# Copy man page to /usr/share/man/man1
cp /opt/coko/lib/python3.7/site-packages/coko-1.0.10-py3.7.egg/share/man/man1/coko.1 /usr/share/man/man1/.
